export const GLOSSARY = {
  // ── Portefeuille ──────────────────────────────────────────────────────────
  PRU:        "Prix de Revient Unitaire — coût moyen d'achat par titre, frais inclus. Sert de référence pour calculer la plus ou moins-value.",
  PEA:        "Plan d'Épargne en Actions — enveloppe fiscale française. Après 5 ans, les gains sont exonérés d'impôt sur le revenu (hors prélèvements sociaux 17,2 %).",
  CTO:        "Compte-Titres Ordinaire — compte sans avantage fiscal, mais sans limite de versement ni restriction géographique.",
  DCA:        "Dollar Cost Averaging — investissement régulier par versements fixes. Lisse le prix d'achat moyen dans le temps et réduit l'impact de la volatilité.",
  TWR:        "Time-Weighted Return — performance pondérée par le temps. Neutralise l'effet des dépôts/retraits pour mesurer la vraie performance de gestion.",
  YTD:        "Year to Date — performance calculée depuis le 1er janvier de l'année en cours.",
  ETF:        "Exchange Traded Fund — fonds indiciel coté en bourse qui réplique un indice (ex : MSCI World). Frais bas, diversification instantanée.",
  ISIN:       "International Securities Identification Number — code unique à 12 caractères qui identifie un titre financier dans le monde entier.",
  CAGR:       "Compound Annual Growth Rate — taux de croissance annuel composé. Mesure la performance moyenne annuelle sur plusieurs années en tenant compte des intérêts composés.",
  PV:         "Plus-Value — gain réalisé ou latent entre votre prix d'achat (PRU) et le cours actuel.",
  MV:         "Moins-Value — perte latente ou réalisée entre votre prix d'achat (PRU) et le cours actuel.",
  SCORING:    "Note attribuée par l'IA (0–20) à chaque position selon les actualités, signaux marché et fondamentaux. Indicatif, pas un conseil.",
  RENFORCER:  "Signal IA : tendance positive, contexte favorable pour augmenter la position dans le cadre d'un DCA.",
  ATTENDRE:   "Signal IA : contexte neutre, pas de catalyseur identifié ce mois. Maintenir sans renforcer.",
  PRUDENCE:   "Signal IA : risques identifiés, éviter d'investir ce mois sur cette valeur.",
  DIVIDENDE:  "Part des bénéfices distribuée par la société à ses actionnaires, généralement en numéraire chaque année.",
  SNAPSHOT:   "Photo instantanée de la valeur totale de votre portefeuille à une date donnée. Sert de référence pour calculer les performances.",
  HORIZON:    "Durée pendant laquelle vous prévoyez de conserver vos investissements sans les toucher.",

  // ── Analyse technique ────────────────────────────────────────────────────
  RSI:        "Relative Strength Index — oscillateur (0–100) qui mesure la vitesse et l'amplitude des variations de cours. Au-dessus de 70 : surachat (possible retournement baissier). En dessous de 30 : survente (possible rebond).",
  MACD:       "Moving Average Convergence Divergence — indicateur de tendance qui compare deux moyennes mobiles (12 et 26 jours). Un croisement de la ligne MACD au-dessus de sa signal line est un signal haussier.",
  "MOYENNE MOBILE": "Moyenne des cours sur une période donnée (ex : MM20, MM50, MM200). Lisse les variations et identifie la tendance. Si le cours est au-dessus de la MM200, la tendance long terme est haussière.",
  SUPPORT:    "Niveau de prix où la demande est historiquement forte — le cours a rebondi plusieurs fois dessus. Un support cassé devient souvent une résistance.",
  RÉSISTANCE: "Niveau de prix où l'offre est historiquement forte — le cours a buté plusieurs fois dessus. Une résistance franchie devient souvent un support.",
  BREAKOUT:   "Franchissement décisif d'un niveau de support ou de résistance avec du volume. Souvent le signal d'un nouveau mouvement directionnel important.",
  GAP:        "Écart entre le cours de clôture d'un jour et l'ouverture du suivant. Un gap haussier indique une forte demande à l'ouverture ; un gap baissier une forte pression vendeuse.",
  BOUGIE:     "Représentation graphique d'une séance : corps (ouverture → clôture) + mèches (plus haut / plus bas). Une bougie verte = clôture au-dessus de l'ouverture (haussier). Rouge = inverse.",
  VOLUME:     "Nombre de titres échangés sur une période. Un mouvement de cours accompagné de volumes élevés est plus fiable qu'un mouvement en faible volume.",
  "FIBONACCI": "Niveaux de retracement (23,6 %, 38,2 %, 61,8 %) calculés depuis un mouvement de cours. Utilisés pour anticiper les zones de rebond ou de consolidation après une tendance forte.",
  ATH:        "All-Time High — plus haut cours historique atteint par un titre. Un franchissement de l'ATH en clôture est un signal haussier fort.",
  "52S HAUT":  "Plus haut cours atteint sur les 52 dernières semaines (1 an glissant). Un cours proche de son plus haut 52 semaines indique une tendance haussière récente.",
  "52S BAS":   "Plus bas cours atteint sur les 52 dernières semaines. Un cours proche de son plus bas 52 semaines peut indiquer une opportunité d'achat ou un titre en difficulté.",
  SURACHAT:   "État d'un titre dont le cours a monté trop vite — les indicateurs (RSI > 70, Bandes de Bollinger) signalent une possible correction à court terme.",
  SURVENTE:   "État d'un titre dont le cours a baissé trop vite — les indicateurs (RSI < 30) signalent un possible rebond technique.",
  CONSOLIDATION: "Phase de stabilisation du cours après une forte hausse ou baisse, sans tendance claire. Le cours évolue dans un range horizontal avant de reprendre sa direction.",
  "BANDES DE BOLLINGER": "Enveloppe formée de 3 courbes autour d'une moyenne mobile. Quand le cours touche la bande supérieure : possible surachat. Bande inférieure : possible survente. Un resserrement précède souvent une forte variation.",

  // ── Analyse fondamentale ─────────────────────────────────────────────────
  PER:        "Price-to-Earnings Ratio (ou P/E) — cours divisé par le bénéfice par action. Mesure ce que le marché accepte de payer pour 1€ de bénéfice. Un PER de 20 = 20 ans de bénéfices au prix actuel.",
  EPS:        "Earnings Per Share (BNA en français) — bénéfice net divisé par le nombre d'actions. Indicateur clé de la rentabilité par titre.",
  "EV/EBITDA": "Valeur d'Entreprise divisée par l'EBITDA — multiple de valorisation qui compare le prix total de l'entreprise (dette incluse) à sa capacité bénéficiaire brute. Plus fiable que le PER pour comparer des entreprises endettées.",
  ROE:        "Return on Equity — bénéfice net / capitaux propres. Mesure la rentabilité générée pour les actionnaires. Un ROE > 15 % est généralement considéré comme solide.",
  "FREE CASH FLOW": "Flux de trésorerie libre — bénéfice opérationnel moins les investissements. L'argent réellement disponible pour rembourser la dette, verser des dividendes ou racheter des actions.",
  EBITDA:     "Earnings Before Interest, Taxes, Depreciation & Amortization — résultat avant intérêts, impôts et amortissements. Approximation du cash généré par l'activité opérationnelle.",
  CAPITALISATION: "Valeur totale de marché d'une entreprise = cours × nombre d'actions. Large cap > 10 Mds€, Mid cap 1–10 Mds€, Small cap < 1 Md€.",
  "FREE FLOAT": "Part du capital réellement disponible en bourse (hors actions détenues par les fondateurs/actionnaires de référence). Un free float faible implique une liquidité réduite et une plus grande volatilité.",
  BETA:       "Sensibilité du titre par rapport au marché. Beta > 1 : titre plus volatile que l'indice (amplifie les hausses ET les baisses). Beta < 1 : titre défensif, moins sensible aux variations du marché.",
  ALPHA:      "Surperformance par rapport à l'indice de référence à risque égal. Un alpha positif signifie que le gérant (ou le titre) a fait mieux que le marché.",

  // ── Stratégie & risque ───────────────────────────────────────────────────
  "STOP-LOSS": "Ordre automatique de vente déclenché si le cours descend en dessous d'un seuil défini. Protège contre les pertes importantes en sortant d'une position avant qu'elle ne s'aggrave.",
  "TAKE PROFIT": "Ordre automatique de vente déclenché quand le cours atteint un objectif de gain défini. Permet de sécuriser une plus-value sans avoir à surveiller le marché en permanence.",
  "VENTE À DÉCOUVERT": "Stratégie qui consiste à vendre un titre qu'on ne possède pas (emprunté) en espérant le racheter moins cher. Profit si le cours baisse, perte potentiellement illimitée si le cours monte.",
  LEVIER:     "Mécanisme qui amplifie les gains ET les pertes via l'emprunt. Levier x2 = une hausse de 5 % rapporte 10 %, mais une baisse de 5 % perd 10 %. Réservé aux investisseurs expérimentés.",
  DIVERSIFICATION: "Répartir ses investissements sur plusieurs titres, secteurs et zones géographiques pour réduire le risque global. Un portefeuille diversifié limite l'impact d'une mauvaise performance isolée.",
  LIQUIDITÉ:  "Facilité à acheter ou vendre un titre sans impacter significativement son cours. Une valeur liquide (volume élevé) peut être achetée/vendue rapidement au cours affiché.",
};
