export const GLOSSARY = {
  PRU:      "Prix de Revient Unitaire — votre coût moyen d'achat par titre, frais inclus.",
  PEA:      "Plan d'Épargne en Actions — enveloppe fiscale française. Après 5 ans, les gains sont exonérés d'impôt sur le revenu (hors prélèvements sociaux).",
  CTO:      "Compte-Titres Ordinaire — compte sans avantage fiscal, mais sans limite de versement ni restriction géographique.",
  DCA:      "Dollar Cost Averaging — stratégie d'investissement régulier par versements fixes. Lisse le prix d'achat moyen dans le temps.",
  TWR:      "Time-Weighted Return — performance pondérée par le temps. Neutralise l'effet des dépôts/retraits pour mesurer la vraie performance de gestion.",
  YTD:      "Year to Date — performance calculée depuis le 1er janvier de l'année en cours.",
  ETF:      "Exchange Traded Fund — fonds indiciel coté en bourse qui réplique un indice (ex: MSCI World). Frais bas, diversification instantanée.",
  ISIN:     "International Securities Identification Number — code unique à 12 caractères qui identifie un titre financier dans le monde entier.",
  CAGR:     "Compound Annual Growth Rate — taux de croissance annuel composé. Mesure la performance moyenne annuelle sur plusieurs années.",
  PV:       "Plus-Value — gain réalisé ou latent entre votre prix d'achat (PRU) et le cours actuel.",
  MV:       "Moins-Value — perte latente ou réalisée entre votre prix d'achat (PRU) et le cours actuel.",
  SCORING:  "Note attribuée par l'IA (0–20) à chaque position selon les actualités, signaux marché et fondamentaux. Indicatif, pas un conseil.",
  RENFORCER:"Signal IA : tendance positive, contexte favorable pour augmenter la position dans le cadre d'un DCA.",
  ATTENDRE: "Signal IA : contexte neutre, pas de catalyseur identifié ce mois. Maintenir sans renforcer.",
  PRUDENCE: "Signal IA : risques identifiés, éviter d'investir ce mois sur cette valeur.",
  DIVIDENDE:"Part des bénéfices distribuée par la société à ses actionnaires, généralement en numéraire.",
  SNAPSHOT: "Photo instantanée de la valeur totale de votre portefeuille à une date donnée. Sert de référence pour calculer les performances.",
  HORIZON:  "Durée pendant laquelle vous prévoyez de conserver vos investissements sans les toucher.",
};
