export const TABS = {
  OVERVIEW:   "overview",
  HOME:       "home",
  PORTFOLIO:  "portfolio",
  MARCHE:     "marche",
  PROJECTION: "projection",
  HISTORIQUE: "historique",
  DCA:        "dca",
  OPERATIONS: "operations",
  CHAT:       "chat",
  AUTOPILOT:  "autopilot",
  PROFIL:     "profil",
  SETTINGS:   "settings",
  PLUS:         "plus",
  AI_PORTFOLIO: "ai_portfolio",
};
