export const AUTOPILOT_UNIVERSE = {
  PEA: [
    // ETFs diversifiés → tous profils
    { symbol: "CW8.PA",   isin: "FR0010315150", nom: "Amundi MSCI World",            type: "ETF",    secteur: "ETF Monde",         profil_min: "prudent" },
    { symbol: "WPEA.PA",  isin: "FR0013412285", nom: "Amundi World PEA",             type: "ETF",    secteur: "ETF Monde",         profil_min: "prudent" },
    { symbol: "PAEEM.PA", isin: "FR0013412020", nom: "Amundi MSCI Emerging Markets", type: "ETF",    secteur: "ETF Émergents",     profil_min: "prudent" },
    { symbol: "PUST.PA",  isin: "FR0013412683", nom: "Amundi PEA S&P 500 ESG",      type: "ETF",    secteur: "ETF USA",           profil_min: "prudent" },
    { symbol: "LYPS.PA",  isin: "LU1781541179", nom: "Amundi S&P 500",              type: "ETF",    secteur: "ETF USA",           profil_min: "prudent" },
    { symbol: "PANX.PA",  isin: "FR0011871110", nom: "Amundi PEA Nasdaq-100",       type: "ETF",    secteur: "ETF Tech",          profil_min: "prudent" },
    { symbol: "PCEU.PA",  isin: "FR0010261198", nom: "Amundi MSCI Europe",          type: "ETF",    secteur: "ETF Europe",        profil_min: "prudent" },
    { symbol: "ESE.PA",   isin: "IE00B4L5Y983", nom: "iShares Core MSCI Europe",    type: "ETF",    secteur: "ETF Europe",        profil_min: "prudent" },
    { symbol: "EWLD.PA",  isin: "IE00B4L5YX21", nom: "iShares MSCI World Swap PEA", type: "ETF",    secteur: "ETF Monde",         profil_min: "prudent" },
    // Blue chips solides → équilibré+
    { symbol: "AI.PA",    isin: "FR0000120073", nom: "Air Liquide",                 type: "Action", secteur: "Industrie",         profil_min: "equilibre" },
    { symbol: "MC.PA",    isin: "FR0000121014", nom: "LVMH",                        type: "Action", secteur: "Luxe",              profil_min: "equilibre" },
    { symbol: "TTE.PA",   isin: "FR0014000MR3", nom: "TotalEnergies",               type: "Action", secteur: "Énergie",           profil_min: "equilibre" },
    { symbol: "SAN.PA",   isin: "FR0000120578", nom: "Sanofi",                      type: "Action", secteur: "Santé",             profil_min: "equilibre" },
    { symbol: "OR.PA",    isin: "FR0000120321", nom: "L'Oréal",                     type: "Action", secteur: "Cosmétiques",       profil_min: "equilibre" },
    { symbol: "BNP.PA",   isin: "FR0000131104", nom: "BNP Paribas",                 type: "Action", secteur: "Banque",            profil_min: "equilibre" },
    { symbol: "AXA.PA",   isin: "FR0000120628", nom: "AXA",                         type: "Action", secteur: "Assurance",         profil_min: "equilibre" },
    { symbol: "SU.PA",    isin: "FR0000121972", nom: "Schneider Electric",          type: "Action", secteur: "Industrie",         profil_min: "equilibre" },
    { symbol: "EL.PA",    isin: "FR0000121667", nom: "EssilorLuxottica",            type: "Action", secteur: "Santé",             profil_min: "equilibre" },
    { symbol: "ASML.AS",  isin: "NL0010273215", nom: "ASML Holding",                type: "Action", secteur: "Semi-conducteurs",  profil_min: "equilibre" },
    { symbol: "SAP.DE",   isin: "DE0007164600", nom: "SAP",                         type: "Action", secteur: "Tech",              profil_min: "equilibre" },
    { symbol: "SIE.DE",   isin: "DE0007236101", nom: "Siemens",                     type: "Action", secteur: "Industrie",         profil_min: "equilibre" },
    // Actions plus volatiles → dynamique+
    { symbol: "CAP.PA",   isin: "FR0000125338", nom: "Capgemini",                   type: "Action", secteur: "Tech",              profil_min: "dynamique" },
    { symbol: "DSY.PA",   isin: "FR0014003TT8", nom: "Dassault Systèmes",           type: "Action", secteur: "Tech",              profil_min: "dynamique" },
    { symbol: "STM.PA",   isin: "NL0000226223", nom: "STMicroelectronics",          type: "Action", secteur: "Semi-conducteurs",  profil_min: "dynamique" },
    { symbol: "SAF.PA",   isin: "FR0000073272", nom: "Safran",                      type: "Action", secteur: "Aéronautique",      profil_min: "dynamique" },
    { symbol: "AIR.PA",   isin: "NL0000235190", nom: "Airbus",                      type: "Action", secteur: "Aéronautique",      profil_min: "dynamique" },
    { symbol: "RMS.PA",   isin: "FR0000052292", nom: "Hermès",                      type: "Action", secteur: "Luxe",              profil_min: "dynamique" },
    { symbol: "GLE.PA",   isin: "FR0000130809", nom: "Société Générale",            type: "Action", secteur: "Banque",            profil_min: "dynamique" },
    { symbol: "DG.PA",    isin: "FR0000125486", nom: "Vinci",                       type: "Action", secteur: "Infrastructure",    profil_min: "dynamique" },
    { symbol: "LR.PA",    isin: "FR0010307819", nom: "Legrand",                     type: "Action", secteur: "Industrie",         profil_min: "dynamique" },
    { symbol: "MT.AS",    isin: "LU1598757687", nom: "ArcelorMittal",               type: "Action", secteur: "Métaux",            profil_min: "dynamique" },
    { symbol: "IFX.DE",   isin: "DE0006231004", nom: "Infineon Technologies",       type: "Action", secteur: "Semi-conducteurs",  profil_min: "dynamique" },
    { symbol: "UCB.BR",   isin: "BE0003739530", nom: "UCB Pharma",                  type: "Action", secteur: "Biotech",           profil_min: "dynamique" },
    // Actions haute volatilité / croissance → très dynamique
    { symbol: "SOI.PA",   isin: "FR0012451430", nom: "Soitec",                      type: "Action", secteur: "Semi-conducteurs",  profil_min: "tres-dynamique" },
    { symbol: "OVH.PA",   isin: "FR0014005HJ9", nom: "OVHcloud",                    type: "Action", secteur: "Cloud",             profil_min: "tres-dynamique" },
    { symbol: "ALO.PA",   isin: "FR0010220475", nom: "Alstom",                      type: "Action", secteur: "Transports",        profil_min: "tres-dynamique" },
    { symbol: "HO.PA",    isin: "FR0000120271", nom: "Thales",                      type: "Action", secteur: "Défense",           profil_min: "tres-dynamique" },
    { symbol: "AM.PA",    isin: "FR0014004L86", nom: "Dassault Aviation",           type: "Action", secteur: "Défense",           profil_min: "tres-dynamique" },
    { symbol: "ERF.PA",   isin: "FR0014000MR3", nom: "Eurofins Scientific",         type: "Action", secteur: "Biotech",           profil_min: "tres-dynamique" },
    { symbol: "BIOR.PA",  isin: "FR0013280286", nom: "BioMérieux",                  type: "Action", secteur: "Biotech",           profil_min: "tres-dynamique" },
    { symbol: "MELE.PA",  isin: "BE0165385973", nom: "Melexis",                     type: "Action", secteur: "Semi-conducteurs",  profil_min: "tres-dynamique" },
    { symbol: "RNO.PA",   isin: "FR0000131906", nom: "Renault",                     type: "Action", secteur: "Automobile",        profil_min: "tres-dynamique" },
    { symbol: "STLA.PA",  isin: "NL00150001Q9", nom: "Stellantis",                  type: "Action", secteur: "Automobile",        profil_min: "tres-dynamique" },
    { symbol: "PUB.PA",   isin: "FR0000130577", nom: "Publicis",                    type: "Action", secteur: "Médias/IA",         profil_min: "tres-dynamique" },
    { symbol: "KER.PA",   isin: "FR0000121485", nom: "Kering",                      type: "Action", secteur: "Luxe",              profil_min: "tres-dynamique" },
    { symbol: "ENGI.PA",  isin: "FR0010208488", nom: "Engie",                       type: "Action", secteur: "Énergie",           profil_min: "tres-dynamique" },
    // Small caps PEA
    { symbol: "ALWLX.PA", isin: "FR0014000TB2", nom: "Wallix Group",                type: "Action", secteur: "Cybersécurité FR",   profil_min: "tres-dynamique" },
    { symbol: "BLV.PA",   isin: "FR0014003FE9", nom: "Believe",                     type: "Action", secteur: "Musique numérique",  profil_min: "tres-dynamique" },
    { symbol: "SWP.PA",   isin: "FR0004188670", nom: "Sword Group",                 type: "Action", secteur: "IT Services",        profil_min: "tres-dynamique" },
    { symbol: "ALHAF.PA", isin: "FR0014007T10", nom: "Haffner Energy",              type: "Action", secteur: "Hydrogène vert",     profil_min: "tres-dynamique" },
    { symbol: "ALNSE.PA", isin: "FR0004054427", nom: "Nanobiotix",                  type: "Action", secteur: "Biotech nano",       profil_min: "tres-dynamique" },
    { symbol: "VIRP.PA",  isin: "FR0000031577", nom: "Virbac",                      type: "Action", secteur: "Santé animale",      profil_min: "tres-dynamique" },
    { symbol: "FNAC.PA",  isin: "FR0012097166", nom: "Fnac Darty",                  type: "Action", secteur: "Retail tech",        profil_min: "tres-dynamique" },
  ],
  CTO: [
    // ETFs → tous profils
    { symbol: "IWDA.AS",  isin: "IE00B4L5Y983", nom: "iShares Core MSCI World",     type: "ETF",    secteur: "ETF Monde",         profil_min: "prudent" },
    { symbol: "VWRA.L",   isin: "IE00BK5BQT80", nom: "Vanguard FTSE All-World",     type: "ETF",    secteur: "ETF Monde",         profil_min: "prudent" },
    { symbol: "SPY",      isin: "US78462F1030", nom: "SPDR S&P 500 ETF",            type: "ETF",    secteur: "ETF USA",           profil_min: "prudent" },
    { symbol: "QQQ",      isin: "US46090E1038", nom: "Invesco Nasdaq-100",          type: "ETF",    secteur: "ETF Tech",          profil_min: "prudent" },
    { symbol: "VTI",      isin: "US9229087690", nom: "Vanguard Total Stock Market", type: "ETF",    secteur: "ETF USA",           profil_min: "prudent" },
    // Blue chips → équilibré+
    { symbol: "AAPL",     isin: "US0378331005", nom: "Apple",                       type: "Action", secteur: "Tech",              profil_min: "equilibre" },
    { symbol: "MSFT",     isin: "US5949181045", nom: "Microsoft",                   type: "Action", secteur: "Tech",              profil_min: "equilibre" },
    { symbol: "GOOGL",    isin: "US02079K3059", nom: "Alphabet",                    type: "Action", secteur: "Tech",              profil_min: "equilibre" },
    { symbol: "AMZN",     isin: "US0231351067", nom: "Amazon",                      type: "Action", secteur: "E-commerce",        profil_min: "equilibre" },
    { symbol: "BRK-B",    isin: "US0846707026", nom: "Berkshire Hathaway B",        type: "Action", secteur: "Financier",         profil_min: "equilibre" },
    { symbol: "JNJ",      isin: "US4781601046", nom: "Johnson & Johnson",           type: "Action", secteur: "Santé",             profil_min: "equilibre" },
    { symbol: "V",        isin: "US92826C8394", nom: "Visa",                        type: "Action", secteur: "Financier",         profil_min: "equilibre" },
    { symbol: "JPM",      isin: "US46625H1005", nom: "JPMorgan Chase",              type: "Action", secteur: "Banque",            profil_min: "equilibre" },
    // Croissance → dynamique+
    { symbol: "NVDA",     isin: "US67066G1040", nom: "NVIDIA",                      type: "Action", secteur: "Semi-conducteurs/IA",profil_min: "dynamique" },
    { symbol: "META",     isin: "US30303M1027", nom: "Meta Platforms",              type: "Action", secteur: "Tech/IA",           profil_min: "dynamique" },
    { symbol: "TSLA",     isin: "US88160R1014", nom: "Tesla",                       type: "Action", secteur: "Automobile",        profil_min: "dynamique" },
    { symbol: "TSM",      isin: "US8740391003", nom: "TSMC",                        type: "Action", secteur: "Semi-conducteurs",  profil_min: "dynamique" },
    { symbol: "AMD",      isin: "US0079031078", nom: "Advanced Micro Devices",      type: "Action", secteur: "Semi-conducteurs",  profil_min: "dynamique" },
    { symbol: "AVGO",     isin: "US11135F1012", nom: "Broadcom",                    type: "Action", secteur: "Semi-conducteurs",  profil_min: "dynamique" },
    { symbol: "XOM",      isin: "US30231G1022", nom: "ExxonMobil",                  type: "Action", secteur: "Énergie",           profil_min: "dynamique" },
    // Haute volatilité / growth → très dynamique
    { symbol: "PLTR",     isin: "US69608A1088", nom: "Palantir Technologies",       type: "Action", secteur: "IA/Data",           profil_min: "tres-dynamique" },
    { symbol: "CRWD",     isin: "US2270461096", nom: "CrowdStrike",                 type: "Action", secteur: "Cybersécurité",     profil_min: "tres-dynamique" },
    { symbol: "SHOP",     isin: "CA82509L1076", nom: "Shopify",                     type: "Action", secteur: "E-commerce",        profil_min: "tres-dynamique" },
    { symbol: "COIN",     isin: "US19260Q1076", nom: "Coinbase",                    type: "Action", secteur: "Crypto/Finance",    profil_min: "tres-dynamique" },
    { symbol: "MELI",     isin: "US58733R1023", nom: "MercadoLibre",                type: "Action", secteur: "E-commerce EM",     profil_min: "tres-dynamique" },
    { symbol: "SMCI",     isin: "US86800U1043", nom: "Super Micro Computer",        type: "Action", secteur: "Serveurs IA",       profil_min: "tres-dynamique" },
    { symbol: "ARM",      isin: "US0420682058", nom: "Arm Holdings",                type: "Action", secteur: "Semi-conducteurs",  profil_min: "tres-dynamique" },
    { symbol: "SQ",       isin: "US8522341036", nom: "Block (Square)",              type: "Action", secteur: "Fintech",           profil_min: "tres-dynamique" },
    { symbol: "RKLB",     isin: "US7731341043", nom: "Rocket Lab",                  type: "Action", secteur: "Espace",            profil_min: "tres-dynamique" },
    { symbol: "IONQ",     isin: "US4624881017", nom: "IonQ",                        type: "Action", secteur: "Quantique",         profil_min: "tres-dynamique" },
    // Small/mid caps US — niches à fort potentiel
    { symbol: "APP",      isin: "US03783C1009", nom: "AppLovin",                    type: "Action", secteur: "AdTech/IA",          profil_min: "tres-dynamique" },
    { symbol: "AXON",     isin: "US05464C1018", nom: "Axon Enterprise",             type: "Action", secteur: "Sécurité publique",  profil_min: "tres-dynamique" },
    { symbol: "DUOL",     isin: "US26617R2094", nom: "Duolingo",                    type: "Action", secteur: "EdTech",             profil_min: "tres-dynamique" },
    { symbol: "MNDY",     isin: "IL0011294286", nom: "Monday.com",                  type: "Action", secteur: "SaaS productivité",  profil_min: "tres-dynamique" },
    { symbol: "CELH",     isin: "SE0083615104", nom: "Celsius Holdings",            type: "Action", secteur: "Boissons santé",     profil_min: "tres-dynamique" },
    { symbol: "RXRX",     isin: "US75629W2080", nom: "Recursion Pharma",            type: "Action", secteur: "IA / Drug discovery",profil_min: "tres-dynamique" },
    { symbol: "LUNR",     isin: "US46125F1049", nom: "Intuitive Machines",          type: "Action", secteur: "Espace / Lune",      profil_min: "tres-dynamique" },
    { symbol: "ACHR",     isin: "US03945R1023", nom: "Archer Aviation",             type: "Action", secteur: "eVTOL / Air taxi",   profil_min: "tres-dynamique" },
    { symbol: "JOBY",     isin: "US4771552089", nom: "Joby Aviation",               type: "Action", secteur: "eVTOL / Air taxi",   profil_min: "tres-dynamique" },
    { symbol: "HIMS",     isin: "US4330001060", nom: "Hims & Hers Health",          type: "Action", secteur: "Santé numérique",    profil_min: "tres-dynamique" },
    { symbol: "SOUN",     isin: "US83602V1061", nom: "SoundHound AI",               type: "Action", secteur: "IA vocale",          profil_min: "tres-dynamique" },
    { symbol: "ALAB",     isin: "US04626L1035", nom: "Astera Labs",                 type: "Action", secteur: "Semi / IA infra",    profil_min: "tres-dynamique" },
    { symbol: "CAVA",     isin: "US14965Q1067", nom: "CAVA Group",                  type: "Action", secteur: "Restauration niche", profil_min: "tres-dynamique" },
  ],
};

export async function fetchYahooPrices(symbols) {
  const endpoint = "/api/yahoo";
  const res = await fetch(`${endpoint}?symbols=${encodeURIComponent(symbols.join(","))}`);
  if (!res.ok) throw new Error(`Yahoo Finance: ${res.status}`);
  const data = await res.json();
  return data?.quoteResponse?.result || [];
}
